---
language: java
jdk:
  - oraclejdk8

bundler_args: "--without eclipse"
before_script:
  - bundle install
  - sudo apt-get update -qq
  - sudo apt-get install firefox xvfb
  - sudo Xvfb :10 -ac &
script:
  - DISPLAY=:10 buildr
